apiVersion: v2
name: crypto-orchestrator
description: A Helm chart for the 2026 CryptoOrchestrator Stack
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: timescale
    version: 0.1.0
    repository: https://charts.timescale.com
    condition: timescale.enabled
