apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cryptoorchestrator

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - postgres.yaml
  - redis.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - celery-worker.yaml
  - ingress.yaml

commonLabels:
  app: cryptoorchestrator
  managed-by: kustomize
